version: '2'
services:
  carts-db:
    image: mongo:3.0.4
    restart: always
    volumes:
      - ./database:/data
    ports:
      - "27017:27017"
  carts:
    image: arijmansour/pfe_carts_microservices:$BUILD_NUMBER
    hostname: pfe_carts_microservices
    restart: always
    ports:
      - "8081:80"
