version: '2'

services:
  spring_boot_mongo:
    build: .
    ports:
      - "8080:80"
  carts:
    image: weaveworksdemos/carts
    hostname: carts
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - reschedule=on-node-failure
      - ZIPKIN_HOST=zipkin
      - ZIPKIN_ENABLED=true
      - SPRING_DATA_MONGODB_.HOST=mongo
   
  zipkin:
    image: openzipkin/zipkin 
    hostname: zipkin
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - reschedule=on-node-failure
    ports:
      - "9411:9411"
